image:
  repository: ghcr.io/shopifake/shopifake-front
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # className: "traefik"
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: web
  # hosts:
  #   - host: shopifake.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #   - host: "*.shopifake.com"
  #     paths:
  #       - path: /
  #         pathType: Prefix


resources: {}

imagePullSecretName: ghcr-secret
podAnnotations: {}
