apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopifake-front.fullname" . }}
  labels:
    app: {{ include "shopifake-front.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "shopifake-front.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "shopifake-front.name" . }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      containers:
        - name: shopifake-front
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.resources | nindent 12 }}
